export const MODEL_TYPES = {
  DOUBLE_WIDE: 2,
  PARK_MODEL: 4,
  SINGLE_WIDE: 1,
  TRIPLE_WIDE: 3,
  UNSPECIFIED: 5
}

export const LISTING_TYPES = {
  FOR_PURCHASE: 1,
  FOR_RENT: 2,
  FOR_RENT_TO_OWN: 3
}
